blank_issues_enabled: false
contact_links:
  - name: ğŸ“ Global StephanusDai Discussions
    url: https://github.com/wiefunkdai/.github/discussions
    about: Please ask and answer questions here.
  - name: ğŸ‘‰ Visit StephanusDai Official Website
    url: https://stephanusdai.web.id/
    about: Learn more about me
